base-nova: avoid using same id for gsi/msi alloc
Up to now it may happen, that the chosen vector used for MSI/MSI-X is the same
for two drivers, when the both drivers use the same irq parameter
during IRQ session construction. Actually, the parameter is not relevant for
the MSI construction, only a unique selector for communication with the kernel
is required.  Tough, allocate a core internal selector dynamically from a
valid range for MSIs.

Issue #5858

Avoids errors alike during IO_MMU faults notification (X201 output):

[init -> platform] Error: Fault: hi=0x8000000500000010, reason=0x5, type=0x0, AT=0x0, EXE=0x0, PRIV=0x0, PP=0x0, Source=0x10, info=0xffffff
Error: unavailable IRQ 1 requested - irq_number=1, device_config_phys=0xe0010000, bdf=0x10, irq_type=1, label="init -> platform -> 1", ram_quota=466, cap_quota=2
[init -> log_kernel -> log] [ 2] CORE:00:02:0 6:25:5:4 [3] Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz MWAIT+E+I
[init -> drivers_init -> intel_fb]   0x40000000 .. 0x4fffffff: stack area
[init -> drivers_init -> intel_fb]   0x30000 .. 0x171fff: ld.lib.so
[init -> gpu] Aperture max: 256M display: 224M
[ 0] sys_assign_gsi: Non-SM CAP (0x3434)
[init -> drivers_init -> ps2] Using keyboard with scan code set 1 (xlate)
[init -> log_kernel -> log] [ 0] IOMMU:0xffffffff817e50b0 FRR:0 FR:0x5 BDF:0:2:0 FI:0xffffff000 (0)
[init -> log_kernel -> log] [ 0] sys_assign_gsi: Non-SM CAP (0x3434)
Error: setting up MSI failed - error 4
[ 0] sys_assign_gsi: Non-SM CAP (0x3434)
Error: setting up MSI failed - error 4
[init -> log_kernel -> log] [ 0] sys_assign_gsi: Non-SM CAP (0x3434)
Warning: Irq could not be de-associated