nic_router: fix state of packet waiting for ARP
This prevents duplicate packet acks and, thus, the following error on
the client side when the ack'd packet is released.

  Error: Bit_array: invalid clear